# Generated by Django 4.1.4 on 2022-12-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('NoteId', models.AutoField(primary_key=True, serialize=False)),
                ('NoteTitle', models.CharField(max_length=100)),
                ('NoteContent', models.CharField(max_length=5000)),
                ('NoteCreated', models.DateField()),
            ],
        ),
    ]
