# Generated by Django 4.1.4 on 2022-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='NoteContent',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='notes',
            name='NoteTitle',
            field=models.CharField(max_length=10000),
        ),
    ]
