# Generated by Django 4.1.4 on 2022-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0002_alter_notes_notecontent_alter_notes_notetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='NoteCreated',
            field=models.DateTimeField(),
        ),
    ]
