# Generated by Django 4.1.4 on 2022-12-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0003_alter_notes_notecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='NoteCreated',
            field=models.DateField(),
        ),
    ]
